### ISSUE TITLE
Looping: WARN  Cannot connect to the database. Let's set it up.

### ISSUE THREAD

**Issue by viasux** [koel/docker#178]
I keep getting the error, "WARN Cannot connect to the database. Let's set it up."

relevant output from docker ps:
```
8351417fe0ad   phanan/koel                       "koel-entrypoint apa…"   18 minutes ago   Up 18 minutes (healthy)             80/tcp, 0.0.0.0:87->87/tcp, :::87->87/tcp                               docker_koel_1
b154ac65a56f   postgres:13                       "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes                       5432/tcp                                                                docker_database_1
```
docker exec --user www-data -it docker_koel_1 bash
www-data@:~/html$ php artisan koel:init --no-assets:
``` 
Your DB driver of choice [MySQL/MariaDB]:
  [mysql     ] MySQL/MariaDB
  [pgsql     ] PostgreSQL
  [sqlsrv    ] SQL Server
  [sqlite-e2e] SQLite
 > pgsql

 DB host:
 > docker_database_1

 DB port (leave empty for default):
 > (tried 5432, 87:87 (what was in compose), and default)

 DB name:
 > koel

 DB user:
 > koel

 DB password:
 > password from compose

   WARN  Cannot connect to the database. Let's set it up.  
```

docker compose:
```
services:
  koel:
    image: phanan/koel
    depends_on:
      - database
    ports:
      - 87:87
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_USERNAME=koel
      - DB_PASSWORD=password
      - DB_DATABASE=koel
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes

  database:
    image: postgres:13
    volumes:
      - db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=koel
      - POSTGRES_USER=koel
      - POSTGRES_PASSWORD=password (same as before, not sure if this was supposed to be a different password?)

**Comment by viasux** [comment]
probably #168 is the fix

**Comment by viasux** [comment]
even with updated docker-compose, the issue persists:
```
version: '3'

services:
  koel:
    image: phanan/koel
    depends_on:
      - database
    ports:
      - 87:87
    environment:
      - DB_PORT=5432
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_USERNAME=koel
      - DB_PASSWORD=bdX*dJd$j&FkGWGztQt6DjJ#uACNxYK4*YVbEP8S@sVqek6SoWb25#4pRKGVNT^yb6QCVBs2BGTJoqf^WXNpbF*xcPoEkgfM%Npv4N7F7aKFB6b&QDMNcXSFTzY&8S*F
      - DB_DATABASE=koel
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes

  database:
    image: postgres:13
    volumes:
      - db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=koel
      - POSTGRES_USER=koel
      - POSTGRES_PASSWORD=bdX*dJd$j&FkGWGztQt6DjJ#uACNxYK4*YVbEP8S@sVqek6SoWb25#4pRKGVNT^yb6QCVBs2BGTJoqf^WXNpbF*xcPoEkgfM%Npv4N7F7aKFB6b&QDMNcXSFTzY&8S*F

volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local
```

**Comment by viasux** [comment]
even with the updated docker-compose, the issue persists:
```
version: '3'

services:
  koel:
    image: phanan/koel
    depends_on:
      - database
    ports:
      - 87:87
    environment:
      - DB_PORT=5432
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_USERNAME=koel
      - DB_PASSWORD=password
      - DB_DATABASE=koel
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes

  database:
    image: postgres:13
    volumes:
      - db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=koel
      - POSTGRES_USER=koel
      - POSTGRES_PASSWORD=password
volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local
```
